In [1]:
import cv2
import numpy as np
import face_recognition
import os

In [2]:
path = r"D:\Attendance System Model\Images"
images = []
classNames = []
myList = os.listdir(path)
print(myList)

['Donald Trump.jpg', 'Joe Biden.gif', 'Test Image.gif']


In [3]:
for cl in myList:
    curImg = cv2.imread(f'{path}/{cl}')
    images.append(curImg)
    classNames.append(os.path.splitext(cl)[0])
print(classNames)

['Donald Trump', 'Joe Biden', 'Test Image']


In [4]:
import cv2

# Load the image
image = cv2.imread(r"D:\Attendance System Model\Images\Donald Trump.jpg")

# Check if the image is loaded successfully
if image is None:
    print("Error: Image not loaded")
else:
    print("Image loaded successfully")
    # Display the image
    cv2.imshow('Loaded Image', image)
    cv2.waitKey(0)
    cv2.destroyAllWindows()



Image loaded successfully


In [5]:
cap = cv2.VideoCapture(0)
while True:
    success, img = cap.read()
    print(img)
    imgS = cv2.resize(img,(0,0),None,.25,.25)
    imgS = cv2.cvtColor(imgS,cv2.COLOR_BGR2RGB)
    facesCurFrame = face_recognition.face_Locations(imgS)
    encodeCurFrame = face_recognition.face_encodings(imgS,facesCurFrame)
    for encodeFace,faceLoc in zip(encodeCurFrame,facesCurFrame):
        matches = face_recognition.Capture.faces(encodeListKnown,encodeface)
        faceDis = face_recognition.face_distance(encodeListKnown,encodeface)
#print(faceDis)
        matchIndex = np.argmin(faceDis)
    if matches [matchIndex]:
        name = classNames[matchIndex].upper()
print(name)

[[[ 75  81  81]
  [ 83  90  90]
  [ 78  87  87]
  ...
  [158 142 136]
  [161 143 139]
  [158 140 137]]

 [[ 82  86  88]
  [ 78  83  85]
  [ 80  88  89]
  ...
  [158 145 140]
  [158 143 140]
  [153 138 135]]

 [[ 92  93  97]
  [ 87  90  94]
  [ 85  91  93]
  ...
  [152 145 142]
  [152 143 140]
  [145 136 133]]

 ...

 [[137 142 141]
  [136 141 140]
  [137 142 141]
  ...
  [ 97 126 147]
  [ 93 123 144]
  [ 96 126 148]]

 [[137 144 141]
  [136 143 140]
  [136 143 140]
  ...
  [ 98 125 148]
  [ 93 120 143]
  [ 99 126 149]]

 [[137 145 141]
  [135 143 139]
  [134 142 138]
  ...
  [100 126 150]
  [ 92 118 142]
  [ 98 124 148]]]


AttributeError: module 'face_recognition' has no attribute 'face_Locations'